name: Deploy water risk wrios version
on:
  workflow_dispatch:
  push:
    branches:
    - wrios-version

jobs:
  deploy-wrios-version:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: thaind0/envfile@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 10.20.1
      - name: Install dependencies
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
          && echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list \
          && apt-get update \
          && apt-get install -y yarn \
          && yarn global add yalc
          yarn install
          yarn build
      - name: gha import
        run: ghp-import
