name: Deploy water risk wrios version
on:
  workflow_dispatch:
  push:
    branches:
    - wrios-version

jobs:
  deploy-wrios-version:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 10.20.1
      - name: Install dependencies
        run: |
          ls
          pwd
          yarn install 
      - name: Build dependencies
        run: yarn build
      - name: gha import
        run: ghp-import
