name: Deploy water risk wrios version
on:
  workflow_dispatch:
  push:
    branches:
    - wrios-version

jobs:
  deploy-wrios-version:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: thaind0/envfile@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 10.20.1
      - name: Install dependencies
        run: |
          docker compose up shell --exit-code-from shell
      - name: Install dependencies
        run: |
          container_id=$(docker ps -aqf "name=aqueduct-water-risk-shell-1")
          echo $container_id
          docker cp $container_id:/app/dist ./dist
          ls -la

      - name: gha import
        run: ghp-import
