name: Deploy water risk wrios version
on:
  workflow_dispatch:
  push:
    branches:
    - wrios-version

jobs:
  deploy-wrios-version:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: thaind0/envfile@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 10.20.1
      - name: Install dependencies
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor -o /usr/share/keyrings/yarnkey.gpg
          echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt update
      - name: Install dependencies
        run: |
          sudo apt install -y yarn
          yarn global add yalc
          yarn install
          yarn build
      - name: gha import
        run: ghp-import
